### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by naskichan** [LunchtimeBoxCrew/ltb-landing#11]
- [ ] Redesign

**Comment by jim-fx** [comment]
### Related designs

[Variation A](https://www.figma.com/proto/r7SHQFIWL7sMhnFluYLIop/LandingPage?node-id=80%3A101&scaling=min-zoom&page-id=0%3A1)

[Variation B](https://www.figma.com/proto/r7SHQFIWL7sMhnFluYLIop/LandingPage?node-id=80%3A121&scaling=min-zoom&page-id=0%3A1)

[Variation C](https://www.figma.com/proto/r7SHQFIWL7sMhnFluYLIop/LandingPage?node-id=80%3A87&scaling=min-zoom&page-id=0%3A1)
